services:
  postgres:
    image: postgres:17.0
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER="${DATABASE_USER}"
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB="test_database"
      - DATABASE_HOST="localhost"
      - DATABASE_PORT=${DATABASE_PORT}
      - PGUSER=${DATABASE_USER}
      - BACKEND_PORT=${BACKEND_PORT}
      - FRONTEND_PORT=${FRONTEND_PORT}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    expose:
      - "${DATABASE_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data    

  frontend:
    build: ./app/frontend/app/
    env_file: .env
    environment:
      - FRONTEND_PORT="${FRONTEND_PORT}"
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    expose:
      - "${FRONTEND_PORT}"
#    command: ["npm", "start"]

  backend:
    build: ./app/backend/app
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    expose:
      - "${BACKEND_PORT}"
    env_file: .env
    environment:
      - DATABASE_USER="${DATABASE_USER}"
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME="test_database"
      - DATABASE_HOST="localhost"
      - DATABASE_PORT=${DATABASE_PORT}
      - FRONTEND_PORT=${FRONTEND_PORT}
    depends_on:
      postgres:
        condition: "service_healthy"

volumes:
  db_data:
