version: "2.29.6"

services:
  postgres:
    image: postgres:17.0
    restart: always
    env_file: "./.env.local"
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_ACCESS_KEY}
      - DATABASE_DB="postgres"
      - DATABASE_HOST="localhost"
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    command: ["psql", "-h", "${DATABASE_HOST}", "-d", "${DATABASE_DB}", "-U", "${DATABASE_USER}", "-W", "${DATABASE_PASSWORD}"]

  web:
    build: ./app/
    ports:
      - 8080:8000
    expose:
      - 8080
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_ACCESS_KEY}
      - DATABASE_DB="postgres"
      - DATABASE_HOST="localhost"
    depends_on:
      postgres:
        condition: "service_healthy"
    command: ["node", "start"]

