version: "2.29.6"

services:
  postgres:
    image: postgres:17.0
    restart: always
    env_file: "./.env.local"
    environment:
      - DATABASE_USER=$DB_USER
      - DATABASE_PASSWORD=$DB_PASSWORD
      - DATABASE_DEFAULT_DATABASE="postgres"
      - DATABASE_HOST="localhost"
      - DATABASE_PORT=$DATABASE_PORT
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    expose:
      - "${DATABASE_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    command: ["psql", "-h", "${DATABASE_HOST}", "-p", "${DATABASE_PORT}", -d", "-W", "${DATABASE_PASSWORD}", "${DATABASE_DEFAULT_DATABASE}", "-U", "${DATABASE_USER}" ]

  frontend:
      build: ./frontend/app/
      ports:
        - 80:80
        - 443:443
      environment:
        - DEFAULT_FRONTEND_PATH=${DEFAULT_FRONTEND_PATH}
      command: ["node", "start"]

  backend:
    build: ./app/
    ports:
      - 8080:8000
    expose:
      - 8080
    environment:
      - DATABASE_USER="${DATABASE_USER}"
      - DATABASE_PASSWORD="${DATABASE_PASSWORD}"
      - DATABASE_DEFAULT_DATABASE="postgres"
      - DATABASE_HOST="localhost"
    depends_on:
      postgres:
        condition: "service_healthy"
    command: ["node", "start"]

